import{a as c,S as l,N as d,P as u}from"./assets/vendor-Dnni7gxJ.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function f(r,s,n){const i="https://furniture-store.b.goit.study/api/",e=new URLSearchParams({page:s,limit:n}),t=`${i}${r}?${e.toString()}`;return(await c(t)).data}function p(r){return r>=3.3&&r<=3.7?3.5:r>=3.8&&r<=4.2?4:Math.round(r*2)/2}function m(r){return r.map(({descr:s,name:n,rate:i})=>`
      <div class="swiper-slide">
        <div class="feedback-card">
          <div class="raty" data-score="${p(i)}"></div>
          <p class="feedback-text">"${s}"</p>
          <p class="feedback-name">${n}</p>
        </div>
      </div>
    `).join("")}f("feedbacks",1,10).then(r=>{var t;if(!((t=r.feedbacks)!=null&&t.length))return;const s=document.querySelector(".feedback-from-API");s.innerHTML=m(r.feedbacks),$(".raty").raty({readOnly:!0,half:!0,starType:"i",score(){return $(this).attr("data-score")}});const n=document.querySelector("#prev-btn"),i=document.querySelector("#next-btn");new l(".feedback-swiper",{modules:[d,u],slidesPerView:1,spaceBetween:20,slidesPerGroup:1,watchOverflow:!0,breakpoints:{768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:32}},navigation:{nextEl:i,prevEl:n},pagination:{el:"#feedback-dots",clickable:!0,bulletClass:"dot",bulletActiveClass:"active",renderBullet:(o,a)=>`<div class="${a}"></div>`},on:{init(){e(this)},slideChange(){e(this)},resize(){e(this)}}});function e(o){n.classList.toggle("arrow-disabled",o.isBeginning),i.classList.toggle("arrow-disabled",o.isEnd)}}).catch(r=>console.error("Помилка при отриманні відгуків:",r));
//# sourceMappingURL=index.js.map
