import{a as y,i,S,N as E,P as k}from"./assets/vendor-D3XQsD4s.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const B=document.querySelector(".hero-btn"),q=document.getElementById("feedback");B.addEventListener("click",()=>{q.scrollIntoView({behavior:"smooth"}),(void 0).blur()});const f="https://furniture-store.b.goit.study/api",b=document.querySelectorAll(".category-card"),p=document.querySelector(".furniture-list"),d=document.querySelector(".load-more-button"),v=document.querySelector(".loader");let m="",l=1;function P(){v.classList.remove("hidden")}function A(){v.classList.add("hidden")}async function h(e="",r=1,s=8){P();try{const n=e?`${f}/furnitures?category=${e}&limit=${s}&page=${r}`:`${f}/furnitures?limit=${s}&page=${r}`,o=(await y.get(n)).data;if(!o.furnitures||o.furnitures.length===0){i.info({title:"Увага",message:"Більше товарів цієїкатегорії немає в наявності",position:"topRight"}),d.disabled=!0;return}C(o.furnitures,r===1),o.furnitures.length<s?d.disabled=!0:d.disabled=!1}catch(n){console.error("Помилка при отриманні меблів:",n),i.error({title:"Помилка",message:"Не вдалося завантажити меблі. Спробуйте ще раз.",position:"topRight"})}finally{A()}}function C(e,r=!0){const s=e.map(n=>{const t=n.color.map(o=>`<span class="furniture-color-circle" style="background-color: ${o};"></span>`).join("");return`
          <li class="furniture-card" data-id="${n._id}">
          <img src="${n.images[0]}" alt="${n.name}" class="furniture-image" />
          <h3 class="furniture-name">${n.name}</h3>
          <div class="furniture-colors">${t}</div>
          <p class="furniture-price">${n.price} грн.</p>
          <button type="button" class="details-btn">Детальніше</button>
          </li>
          `}).join("");r?p.innerHTML=s:p.insertAdjacentHTML("beforeend",s)}async function R(){try{const s=await(await fetch(`${f}/categories`)).json();document.querySelectorAll(".category-card").forEach(t=>{const o=t.dataset.name,a=s.find(w=>w.name===o);a&&(t.dataset.id=a._id)})}catch(e){console.error("Помилка при підставці ID категорії:",e),i.error({title:"Помилка",message:"Не вдалося завантажити категорії. Спробуйте ще раз.",position:"topRight"})}}function I(){b.forEach(e=>{e.addEventListener("click",()=>{b.forEach(r=>r.classList.remove("active")),e.classList.add("active"),m=e.dataset.id||"",l=1,h(m,l)})})}d.addEventListener("click",()=>{l+=1,h(m,l)});p.addEventListener("click",e=>{const r=e.target.closest(".details-btn");r&&r.closest(".furniture-card")?.dataset.id});async function M(){await R(),I(),h()}M();async function O(e,r,s){const n="https://furniture-store.b.goit.study/api/",t=new URLSearchParams({page:r,limit:s}),o=`${n}${e}?${t.toString()}`;return(await y(o)).data}function x(e){return e>=3.3&&e<=3.7?3.5:e>=3.8&&e<=4.2?4:Math.round(e*2)/2}function T(e){return e.map(({descr:r,name:s,rate:n})=>`
      <div class="swiper-slide">
        <div class="feedback-card">
          <div class="raty" data-score="${x(n)}"></div>
          <p class="feedback-text">"${r}"</p>
          <p class="feedback-name">${s}</p>
        </div>
      </div>
    `).join("")}O("feedbacks",1,10).then(e=>{if(!e.feedbacks?.length)return;const r=document.querySelector(".feedback-from-API");r.innerHTML=T(e.feedbacks),$(".raty").raty({readOnly:!0,half:!0,starType:"i",score(){return $(this).attr("data-score")}});const s=document.querySelector("#prev-btn"),n=document.querySelector("#next-btn");new S(".feedback-swiper",{modules:[E,k],slidesPerView:1,spaceBetween:24,slidesPerGroup:1,watchOverflow:!0,breakpoints:{768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}},navigation:{nextEl:n,prevEl:s},pagination:{el:"#feedback-dots",clickable:!0,bulletClass:"dot",bulletActiveClass:"active",renderBullet:(o,a)=>`<div class="${a}"></div>`},on:{init(){t(this)},slideChange(){t(this)},resize(){t(this)}}});function t(o){s.classList.toggle("arrow-disabled",o.isBeginning),n.classList.toggle("arrow-disabled",o.isEnd)}}).catch(e=>{console.error("Помилка при отриманні відгуків:",e),i.show({title:"Помилка",message:e.message||"Не вдалося завантажити відгуки.",position:"topCenter",color:"#ef4040",messageColor:"#fff",titleColor:"#fff"});const r=document.querySelector(".feedback-from-API");r&&(r.innerHTML='<div class="error-text"><p>Не вдалося показати відгуки.</p></div>');const s=document.querySelector("#prev-btn"),n=document.querySelector("#next-btn");s&&(s.disabled=!0,s.classList.add("arrow-disabled")),n&&(n.disabled=!0,n.classList.add("arrow-disabled"))});const j=document.querySelector(".modal-close-btn"),g=document.querySelector(".modal-overlay"),c=document.querySelector(".modal-form");j.addEventListener("click",u);g.addEventListener("click",e=>{e.target===g&&u()});document.addEventListener("keydown",L);function u(){g.classList.toggle("is-open"),document.removeEventListener("keydown",L)}function L(e){e.key==="Escape"&&u()}c.addEventListener("submit",async e=>{e.preventDefault();const r={email:c.elements["user-email"].value,phone:c.elements.phone.value,modelId:"682f9bbf8acbdf505592ac36",color:"#1212ca",comment:c.elements["user-comment"].value};try{const s=await y.post("https://furniture-store.b.goit.study/api/orders",r,{headers:{"Content-Type":"application/json"}});i.success({title:"OK",message:"Замовлення успішно відправлено!",position:"topRight"}),u(),c.reset()}catch(s){console.error("Помилка відправки:",s),i.error({title:"Error",message:s.response.data.message,position:"topRight"})}});
//# sourceMappingURL=index.js.map
